### ISSUE TITLE
Delete command messages if not from collab

### ISSUE THREAD

**Issue by patcon** [eteled/issues#1]
People can still spam via fake commands that they know will fail :)

Example: https://github.com/captn3m0/github-image-post/issues/3#issuecomment-29761914

**Comment by patcon** [comment]
I might suggest that the bot not reply when a non-collab tries to submit a command, and instead just deletes the comment. We could explain that only collabs can submit commands via the initial bot comment.

**Comment by captn3m0** [comment]
Now fixed. [See here](https://github.com/captn3m0/github-image-post/issues/4) for sample behavior.

**Comment by patcon** [comment]
wild.
