### ISSUE TITLE
Detect admins who are org admins

### ISSUE THREAD

**Issue by isaacs** [eteled/issues#4]
If you're in the "admin" group of an org that owns a repo, but not on the "collaborators" list, eteled doesn't respect your authority.

**Comment by captn3m0** [comment]
If eteled tries to access the list of teams on an organization, the web-ui [shows the owners team](https://github.com/organizations/joyent/teams/13987). However, if I make the [same request to the API](https://api.github.com/orgs/joyent/teams), the response doesn't include the owners team (only node and libuv). The API documentation mentions:

> All actions against teams require at a minimum an authenticated user who is a member of the Owners team in the :org being managed. 

As such I don't think getting the owners list is possible without adding @eteled to the owners list, which I recommend against. Hence we are limited to the collaborator list check, which eteled currently uses.

**Comment by isaacs** [comment]
Fair enough.  An owner can add themselves to the collaborator list anyway.
