### ISSUE TITLE
Does eteled work on pull requests?

### ISSUE THREAD

**Issue by mnot** [eteled/issues#7]
Doesn't seem to be...
  https://github.com/http2/http2-spec/pull/366

Thanks,

**Comment by captn3m0** [comment]
Yes, [eteled does support PRs](https://github.com/eteled/issues/pull/8). It seems you forgot to add eteled to the repo collab list. Once you do that, eteled will start honoring any future "START/STOP" requests.

**Comment by mnot** [comment]
It is on the collab list. Does it need admin rights, or just r/w? Thanks.

**Comment by captn3m0** [comment]
R/W should be fine I think. I'll take a deeper look, in that case.

**Comment by captn3m0** [comment]
This should be fixed now. The issue was that eteled wasn't recognizing you as a collaborator, so it didn't accept the command. You can re-add eteled to the repo (its not added currently), and test the command again.
